### ISSUE TITLE
Long - term caching support

### ISSUE THREAD

**Issue by rolznz** [ostyjs/nostr-hooks#14]
Hi,

Any chance you are planning to add support to cache events to localStorage or similar so there is no delay re-fetching events on page refresh?

**Comment by sepehr-safari** [comment]
added in v2. explained in readme.

**Comment by rolznz** [comment]
@sepehr-safari nice work on v2! looking forward to trying it out :sunglasses:

**Comment by sepehr-safari** [comment]
> @sepehr-safari nice work on v2! looking forward to trying it out 😎

thank you! would love to hear your feedback. btw, it's still just the foundation with just a few basic hooks. I will add more useful hooks as well.
