### ISSUE TITLE
Bug: useSubcribe is not working as expected 

### ISSUE THREAD

**Issue by max21dev** [ostyjs/nostr-hooks#20]
changing `filters` array in `useSubscribe` hook doesn't cause any re-subscribe as well as re-render, even if the `filters` is a state.

**Comment by sepehr-safari** [comment]
thanks. it's a known bug. I'll fix it asap.

**Comment by sepehr-safari** [comment]
Fixed in https://github.com/ostyjs/nostr-hooks/pull/22
